import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { App } from "./contracts.js";

export interface GenerateSiteOptions {
  apps: App[];
  outDir: string;
  siteName?: string;
  baseHref?: string;
  generatedAt?: string;
}

export interface GeneratedSite {
  outDir: string;
  pages: string[];
  appCount: number;
}

export function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

export function appVersion(app: App): string | null {
  const version = app.metadata?.["version"];
  return typeof version === "string" && version.length > 0 ? version : null;
}

export function installCommand(app: App): string {
  return `bun add -g ${app.npmName}`;
}

function githubWebUrl(app: App): string {
  return app.githubUrl.replace(/^git\+/, "").replace(/\.git$/, "");
}

function npmUrl(app: App): string {
  return `https://www.npmjs.com/package/${app.npmName}`;
}

const STYLES = `
:root { color-scheme: light dark; --fg: #16181d; --muted: #5c6470; --bg: #ffffff; --card: #f5f6f8; --accent: #2456e6; --border: #e2e5ea; }
@media (prefers-color-scheme: dark) { :root { --fg: #e8eaf0; --muted: #9aa3b2; --bg: #101216; --card: #1a1d23; --accent: #7da2ff; --border: #2a2e36; } }
* { box-sizing: border-box; }
body { margin: 0 auto; max-width: 960px; padding: 2.5rem 1.25rem 4rem; font-family: ui-sans-serif, system-ui, -apple-system, sans-serif; color: var(--fg); background: var(--bg); line-height: 1.55; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
header.site h1 { margin: 0 0 0.25rem; font-size: 1.9rem; }
header.site p { margin: 0 0 2rem; color: var(--muted); }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); gap: 0.9rem; padding: 0; list-style: none; }
.card { border: 1px solid var(--border); background: var(--card); border-radius: 10px; padding: 1rem 1.1rem; }
.card h2 { margin: 0 0 0.3rem; font-size: 1.05rem; }
.card p { margin: 0; color: var(--muted); font-size: 0.88rem; }
.badges { margin-top: 0.6rem; display: flex; flex-wrap: wrap; gap: 0.35rem; }
.badge { display: inline-block; font-size: 0.72rem; padding: 0.12rem 0.5rem; border-radius: 999px; border: 1px solid var(--border); color: var(--muted); }
.badge.version { color: var(--accent); border-color: var(--accent); }
pre.install { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 0.8rem 1rem; overflow-x: auto; font-size: 0.92rem; }
.meta { color: var(--muted); font-size: 0.85rem; }
.links { display: flex; gap: 1rem; margin: 0.8rem 0 1.4rem; }
nav.crumb { margin-bottom: 1.6rem; font-size: 0.9rem; }
footer { margin-top: 3rem; color: var(--muted); font-size: 0.8rem; border-top: 1px solid var(--border); padding-top: 1rem; }
`.trim();

function layout(title: string, body: string, options: GenerateSiteOptions): string {
  const generatedAt = options.generatedAt ?? new Date().toISOString();
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<style>${STYLES}</style>
</head>
<body>
${body}
<footer>Generated by @hasna/catalog on ${escapeHtml(generatedAt)}.</footer>
</body>
</html>
`;
}

export function renderIndexPage(options: GenerateSiteOptions): string {
  const siteName = options.siteName ?? "Hasna App Catalog";
  const cards = options.apps
    .map((app) => {
      const version = appVersion(app);
      return `<li class="card">
<h2><a href="apps/${escapeHtml(app.appId)}/">${escapeHtml(app.appId)}</a></h2>
<p>${escapeHtml(app.summary ?? app.npmName)}</p>
<div class="badges">
${version ? `<span class="badge version">v${escapeHtml(version)}</span>` : ""}
<span class="badge">${escapeHtml(app.lifecycle)}</span>
<span class="badge">${escapeHtml(app.releaseChannel)}</span>
</div>
</li>`;
    })
    .join("\n");
  const body = `<header class="site">
<h1>${escapeHtml(siteName)}</h1>
<p>${options.apps.length} open-source apps, every one installable with Bun.</p>
</header>
<ul class="grid">
${cards}
</ul>`;
  return layout(siteName, body, options);
}

export function renderAppPage(app: App, options: GenerateSiteOptions): string {
  const version = appVersion(app);
  const bins = app.surfaces.bins;
  const body = `<nav class="crumb"><a href="../../">&larr; All apps</a></nav>
<header class="site">
<h1>${escapeHtml(app.appId)}</h1>
<p>${escapeHtml(app.summary ?? app.npmName)}</p>
</header>
<div class="badges">
${version ? `<span class="badge version">v${escapeHtml(version)}</span>` : ""}
<span class="badge">${escapeHtml(app.lifecycle)}</span>
<span class="badge">${escapeHtml(app.releaseChannel)}</span>
</div>
<div class="links">
<a href="${escapeHtml(githubWebUrl(app))}">GitHub</a>
<a href="${escapeHtml(npmUrl(app))}">npm</a>
</div>
<h2>Install</h2>
<pre class="install"><code>${escapeHtml(installCommand(app))}</code></pre>
${bins.length > 0 ? `<p class="meta">Provides: ${bins.map((bin) => `<code>${escapeHtml(bin)}</code>`).join(", ")}</p>` : ""}
<p class="meta">Package: <code>${escapeHtml(app.npmName)}</code> &middot; Repo folder: <code>${escapeHtml(app.repoFolder)}</code></p>`;
  return layout(`${app.appId} — Hasna App Catalog`, body, options);
}

/**
 * Render the public catalog site (index + per-app landing pages) as static
 * HTML into `outDir`. Generation only — deploy is a separate concern.
 */
export function generateSite(options: GenerateSiteOptions): GeneratedSite {
  const apps = [...options.apps].sort((a, b) => a.appId.localeCompare(b.appId));
  const resolved = { ...options, apps };
  mkdirSync(options.outDir, { recursive: true });
  const pages: string[] = [];

  const indexPath = join(options.outDir, "index.html");
  writeFileSync(indexPath, renderIndexPage(resolved));
  pages.push(indexPath);

  for (const app of apps) {
    const appDir = join(options.outDir, "apps", app.appId);
    mkdirSync(appDir, { recursive: true });
    const pagePath = join(appDir, "index.html");
    writeFileSync(pagePath, renderAppPage(app, resolved));
    pages.push(pagePath);
  }

  return { outDir: options.outDir, pages, appCount: apps.length };
}
